IDIR =../include
CC=gcc
CFLAGS=-I$(IDIR) -W -Wall -pedantic -ansi -g -std=gnu99

ODIR=obj
LDIR =../lib

LIBS= -lm

_DEPS = map.h robot.h arduino-serial-lib.h 
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = main.o map.o robot.o arduino-serial-lib.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: %.c $(DEPS)
		$(CC) -c -o $@ $< $(CFLAGS)

prog: $(OBJ)
		$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
		rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ 
